<!--*************************************************
 * Project:     IOManager
 * Author:      Peter C
 * Date:        2026Jul07
 * History:     2026Jul07 - Initial creation
 *              2026Jul07 - Add enabled toggle column and Trash2 delete icon
 *************************************************-->

<template>
  <div class="space-y-6">
    <div>
      <h1 class="text-2xl font-semibold tracking-tight text-slate-100">Virtual Tags</h1>
      <p class="mt-1 text-sm text-slate-500">
        Tags generated by rule engine without a corresponding I/O index row.
        Use <code class="text-amber-400 font-mono text-xs">#N</code> in descriptions to insert the range counter.
      </p>
    </div>

    <div v-if="store.loading" class="text-sm text-slate-500 animate-pulse">Loading…</div>

    <template v-else-if="store.config">
      <!-- Toolbar -->
      <div class="flex items-center justify-between">
        <p class="text-xs text-slate-600 font-mono">{{ rows.length }} entr{{ rows.length === 1 ? 'y' : 'ies' }}</p>
        <button
          class="px-3 py-1 rounded text-xs font-semibold bg-amber-500/10 border border-amber-500/30 text-amber-400 hover:bg-amber-500/20 transition-colors"
          @click="addRow"
        >+ Add Entry</button>
      </div>

      <!-- Empty state -->
      <div
        v-if="rows.length === 0"
        class="rounded-lg border border-slate-800 bg-slate-900/50 px-6 py-12 text-center"
      >
        <p class="text-sm text-slate-500">No virtual tags defined.</p>
        <p class="text-xs text-slate-600 mt-1">Click <span class="text-amber-400">+ Add Entry</span> to create one.</p>
      </div>

      <!-- Table -->
      <div v-else class="rounded-lg border border-slate-800 bg-slate-900 overflow-hidden">
        <div class="overflow-x-auto">
          <table class="text-xs font-mono whitespace-nowrap w-full">
            <thead>
              <tr class="border-b border-slate-800 bg-slate-800/30">
                <th class="px-3 py-2.5 text-center text-slate-500 font-medium">On</th>
                <th class="px-3 py-2.5 text-left text-slate-500 font-medium">From</th>
                <th class="px-3 py-2.5 text-left text-slate-500 font-medium">To <span class="text-slate-700">(optional)</span></th>
                <th class="px-3 py-2.5 text-left text-slate-500 font-medium">Description</th>
                <th class="px-3 py-2.5 text-left text-slate-500 font-medium">Template</th>
                <th class="px-3 py-2.5 text-center text-slate-500 font-medium">Alarm</th>
                <th class="px-3 py-2.5 text-left text-slate-500 font-medium">Alarm Message</th>
                <th class="px-3 py-2.5 text-left text-slate-500 font-medium">Cond</th>
                <th class="px-3 py-2.5 w-8"></th>
              </tr>
            </thead>
            <tbody>
              <tr
                v-for="(row, i) in rows"
                :key="row._key"
                class="border-b border-slate-800/50 last:border-0 hover:bg-slate-800/10 transition-opacity"
                :class="{ 'opacity-40': !row.enabled }"
              >
                <!-- Enabled toggle -->
                <td class="px-2 py-1.5 text-center">
                  <input
                    v-model="row.enabled"
                    type="checkbox"
                    class="accent-amber-500"
                    title="Enable / disable this entry"
                  />
                </td>
                <!-- From -->
                <td class="px-2 py-1.5">
                  <input
                    v-model="row.tag_name_from"
                    type="text"
                    placeholder="PY-001"
                    class="w-24 px-2 py-0.5 rounded bg-slate-800 border border-slate-700 text-amber-300 placeholder-slate-700 focus:outline-none focus:border-amber-500"
                  />
                </td>
                <!-- To -->
                <td class="px-2 py-1.5">
                  <input
                    v-model="row.tag_name_to"
                    type="text"
                    placeholder="PY-010"
                    class="w-24 px-2 py-0.5 rounded bg-slate-800 border border-slate-700 text-amber-300/70 placeholder-slate-700 focus:outline-none focus:border-amber-500"
                  />
                </td>
                <!-- Description -->
                <td class="px-2 py-1.5">
                  <input
                    v-model="row.description"
                    type="text"
                    placeholder="Outlet Pump - #N"
                    class="w-52 px-2 py-0.5 rounded bg-slate-800 border border-slate-700 text-slate-300 placeholder-slate-700 focus:outline-none focus:border-amber-500"
                  />
                </td>
                <!-- Template -->
                <td class="px-2 py-1.5">
                  <select
                    v-model="row.template"
                    class="w-24 px-2 py-0.5 rounded bg-slate-800 border border-slate-700 text-slate-300 focus:outline-none focus:border-amber-500"
                  >
                    <option value="" disabled>— pick —</option>
                    <option
                      v-for="t in store.config?.templates ?? []"
                      :key="t.template"
                      :value="t.template"
                    >{{ t.template }}</option>
                  </select>
                </td>
                <!-- Alarm checkbox -->
                <td class="px-2 py-1.5 text-center">
                  <input v-model="row.is_alarm" type="checkbox" class="accent-amber-500" />
                </td>
                <!-- Alarm message -->
                <td class="px-2 py-1.5">
                  <input
                    v-model="row.alarm_message"
                    type="text"
                    placeholder="Fault message"
                    :disabled="!row.is_alarm"
                    class="w-44 px-2 py-0.5 rounded bg-slate-800 border border-slate-700 text-slate-300 placeholder-slate-700 focus:outline-none focus:border-amber-500 disabled:opacity-30 disabled:cursor-not-allowed"
                  />
                </td>
                <!-- Alarm condition -->
                <td class="px-2 py-1.5">
                  <select
                    v-model="row.alarm_condition"
                    :disabled="!row.is_alarm"
                    class="w-20 px-2 py-0.5 rounded bg-slate-800 border border-slate-700 text-slate-300 focus:outline-none focus:border-amber-500 disabled:opacity-30 disabled:cursor-not-allowed"
                  >
                    <option :value="null">default</option>
                    <option value="POS">POS</option>
                    <option value="NEG">NEG</option>
                  </select>
                </td>
                <!-- Delete -->
                <td class="px-2 py-1.5 text-center">
                  <button
                    :disabled="busy"
                    class="text-slate-600 hover:text-red-400 disabled:opacity-30 transition-colors"
                    title="Delete entry"
                    @click="deleteRow(i)"
                  >
                    <Trash2 :size="13" />
                  </button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <!-- Save -->
      <div class="flex items-center gap-4">
        <button
          :disabled="busy"
          class="px-5 py-2 rounded-md bg-amber-500 hover:bg-amber-400 disabled:opacity-40 disabled:cursor-not-allowed text-sm font-semibold text-slate-950 transition-colors"
          @click="save"
        >{{ busy ? 'Saving…' : 'Save' }}</button>
        <span v-if="saved" class="text-sm text-green-400">Saved.</span>
        <span v-if="saveError" class="text-sm text-red-400">{{ saveError }}</span>
      </div>
    </template>

    <div v-else-if="store.error" class="text-sm text-red-400">{{ store.error }}</div>
  </div>
</template>

<script setup lang="ts">
import { Trash2 } from 'lucide-vue-next'
import type { VirtualTagEntry } from '~/types/api'

type DraftRow = Omit<VirtualTagEntry, 'id'> & { _key: string; _id: string | null }

const store = useConfigStore()
const busy = ref(false)
const saved = ref(false)
const saveError = ref<string | null>(null)
const rows = ref<DraftRow[]>([])

let _keySeq = 0
function newKey() { return String(++_keySeq) }

function vtToRow(vt: VirtualTagEntry): DraftRow {
  return {
    _key: newKey(),
    _id: vt.id,
    tag_name_from: vt.tag_name_from,
    tag_name_to: vt.tag_name_to,
    description: vt.description,
    template: vt.template,
    enabled: vt.enabled,
    is_alarm: vt.is_alarm,
    alarm_condition: vt.alarm_condition,
    alarm_message: vt.alarm_message,
  }
}

function blankRow(): DraftRow {
  return {
    _key: newKey(),
    _id: null,
    tag_name_from: '',
    tag_name_to: null,
    description: '',
    template: store.config?.templates[0]?.template ?? '',
    enabled: true,
    is_alarm: false,
    alarm_condition: null,
    alarm_message: '',
  }
}

onMounted(async () => {
  await store.fetchConfig()
  if (store.config) rows.value = store.config.virtual_tags.map(vtToRow)
})

function addRow() {
  rows.value.push(blankRow())
}

async function deleteRow(index: number) {
  const row = rows.value[index]
  if (row._id) {
    busy.value = true
    try {
      await store.deleteVirtualTag(row._id)
    } catch (e: any) {
      saveError.value = e.data?.detail ?? e.message ?? 'Delete failed'
      busy.value = false
      return
    } finally {
      busy.value = false
    }
  }
  rows.value.splice(index, 1)
}

async function save() {
  saveError.value = null
  const invalid = rows.value.find(r => !r.tag_name_from.trim() || !r.template)
  if (invalid) {
    saveError.value = 'All entries must have a tag name and a template.'
    return
  }

  busy.value = true
  try {
    // Reconcile: delete removed entries, create new, update changed
    const existing = store.config?.virtual_tags ?? []
    const keptIds = new Set(rows.value.filter(r => r._id).map(r => r._id!))

    // Delete entries removed from the list
    for (const vt of existing) {
      if (!keptIds.has(vt.id)) await store.deleteVirtualTag(vt.id)
    }

    // Create or update each row in order
    for (const row of rows.value) {
      const payload: Omit<VirtualTagEntry, 'id'> = {
        tag_name_from: row.tag_name_from.trim(),
        tag_name_to: row.tag_name_to?.trim() || null,
        description: row.description,
        template: row.template,
        enabled: row.enabled,
        is_alarm: row.is_alarm,
        alarm_condition: row.is_alarm ? row.alarm_condition : null,
        alarm_message: row.is_alarm ? row.alarm_message : '',
      }
      if (row._id) {
        await store.updateVirtualTag(row._id, payload)
      } else {
        const created = await store.createVirtualTag(payload)
        row._id = created.id
      }
    }

    saved.value = true
    setTimeout(() => { saved.value = false }, 3000)
  } catch (e: any) {
    saveError.value = e.data?.detail ?? e.message ?? 'Save failed'
  } finally {
    busy.value = false
  }
}
</script>
